name: LobbyAPI-1.0.1
version: '1.0.1'
main: dev.lofiz.lobbyAPI.LobbyAPI
api-version: '1.20'
commands:
  friend:
    description: Manage your friends.
    usage: /friend <add|remove|list> <player>
  ignore:
    description: Manage your ignored players.
    usage: /ignore <add|remove|list> <player>
  profile:
    description: Manage your player profile.
    usage: /profile <create|setting> [<key> <value>]
  party:
    description: Manage your party.
    usage: /party <create|join|leave|kick|disband|warp> [<player>]
  guild:
    description: Manage your guild.
    usage: /guild <create|join|leave|disband> <name>
  mute:
    description: Mute a player.
    usage: /mute <player>
  unmute:
    description: Unmute a player.
    usage: /unmute <player>
  gmc:
    description: Set game mode to creative.
  gms:
    description: Set game mode to survival.
  gmsp:
    description: Set game mode to spectator.
  gma:
    description: Set game mode to adventure.
  discord:
    description: Get the Discord link.
  store:
    description: Get the store link.