mutedPlayers: {}

profiles:
  default-privacy: "public"
  default-notifications: "enabled"

parties:
  max-party-size: 10
  default-party-warp-location: "world,0,64,0"

guilds:
  max-guild-size: 50
  default-guild-warp-location: "world,0,64,0"
profile:
  slots:
    - slot: 19
      material: PAPER
      display_name: "Placeholder 1"
      placeholder: "%example_placeholder1%"
    - slot: 20
      material: PAPER
      display_name: "Placeholder 2"
      placeholder: "%example_placeholder2%"
    - slot: 21
      material: PAPER
      display_name: "Placeholder 3"
      placeholder: "%example_placeholder3%"
    - slot: 22
      material: PAPER
      display_name: "Placeholder 4"
      placeholder: "%example_placeholder4%"
    - slot: 23
      material: PAPER
      display_name: "Placeholder 5"
      placeholder: "%example_placeholder5%"
    - slot: 24
      material: PAPER
      display_name: "Placeholder 6"
      placeholder: "%example_placeholder6%"
