name: LobbyAPI-1.0.1
version: '${project.version}'
main: dev.lofiz.lobbyAPI.LobbyAPI
api-version: '1.20'
commands:
  friend:
    description: Manage friends
    usage: /friend <add|remove|list> [player]
    permission: lobbyapi.friend
    aliases: [f]
  ignore:
    description: Manage ignored players
    usage: /ignore <add|remove|list> [player]
    permission: lobbyapi.ignore
  profile:
    description: Manage player profiles
    usage: /profile view [player]
    permission: lobbyapi.profile
  party:
    description: Manage parties
    usage: /party <create|invite|accept|deny|kick|leave|disband|promote|demote|chat>
    permission: lobbyapi.party
    aliases: [p]
  guild:
    description: Manage guilds
    usage: /guild <create|invite|accept|deny|join|leave|disband|list|chat>
    permission: lobbyapi.guild
    aliases: [g]
  tempban:
    description: Temporarily ban a player
    usage: /tempban <player> <duration> <days|hours|weeks|minutes> [reason]
    permission: lobbyapi.tempban
  mute:
    description: Mute a player
    usage: /mute <player> <duration>
    permission: lobbyapi.mute
  unmute:
    description: Unmute a player
    usage: /unmute <player>
    permission: lobbyapi.unmute
  gmc:
    description: Set game mode to creative
    usage: /gmc
    permission: lobbyapi.gm
  gms:
    description: Set game mode to survival
    usage: /gms
    permission: lobbyapi.gm
  gmsp:
    description: Set game mode to spectator
    usage: /gmsp
    permission: lobbyapi.gm
  gma:
    description: Set game mode to adventure
    usage: /gma
    permission: lobbyapi.gm
  discord:
    description: Get the Discord link
    usage: /discord
    permission: lobbyapi.link
  store:
    description: Get the store link
    usage: /store
    permission: lobbyapi.link
permissions:
  lobbyapi.friend:
    description: Allows use of friend commands
    default: true
  lobbyapi.ignore:
    description: Allows use of ignore commands
    default: true
  lobbyapi.profile:
    description: Allows use of profile commands
    default: true
  lobbyapi.party:
    description: Allows use of party commands
    default: true
  lobbyapi.guild:
    description: Allows use of guild commands
    default: true
  lobbyapi.tempban:
    description: Allows use of tempban command
    default: op
  lobbyapi.mute:
    description: Allows use of mute command
    default: op
  lobbyapi.unmute:
    description: Allows use of unmute command
    default: op
  lobbyapi.gm:
    description: Allows use of game mode commands
    default: op
  lobbyapi.link:
    description: Allows use of link commands
    default: true
